### ISSUE TITLE
Sintesis de Calidad 

### ISSUE THREAD

**Issue by magaly1311** [SistemasTecTlaxiaco/actividad-4-tarea-de-sintesis-de-calidad-magaly1311#1]
[sintesis de la calidad del software.pdf](https://github.com/SistemasTecTlaxiaco/actividad-4-tarea-de-sintesis-de-calidad-magaly1311/files/12704190/sintesis.de.la.calidad.del.software.pdf)

**Comment by Aricel117** [comment]
Calificacion: 20

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
